#%RAML 1.0
title: kalyanLaxmi-api
mediaType: 
- application/json
version: v1.0.0
protocols:
  - HTTP
/account:
  get:
    body:
      application/json:
        example:
          {
            "msg": "Hello Prashanth"
          }
    responses:
      200:
        body:
          application/json:
            example:
              {
                "status": "Hello Prashanth"
              }

 

    